export const ADD_TRANSACTION = 'ADD_TRANSACTION'

export const SET_BUDGET = 'SET_BUDGET'

export const FETCH_USER_BUDGETS = 'FETCH_USER_BUDGETS'

export const START_FETCHING_BUDGET_REQUEST = 'START_FETCHING_BUDGET_REQUEST'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER'
